// admin-react/src/components/ChatPanel.tsx
import { useState, useRef, useEffect, useCallback } from 'react'
import { useAuth } from '@/stores/auth'
import { sdbQuery } from '@/lib/sdb'
import { subscribeAgentMessages } from '@/agent/live-query'
import { dispatchActions, type TableController, type DetailController } from '@/agent/dispatcher'
import type { AgentAction, AgentMessage } from '@/agent/types'

interface ChatMsg {
  id: string
  role: 'user' | 'agent'
  text: string
  status: 'pending' | 'done' | 'error'
  actions: AgentAction[]
  timestamp: string
}

interface Props {
  tableRefs: React.MutableRefObject<Map<string, TableController>>
  currentTable: string
  detailCtrl: DetailController
}

export default function ChatPanel({ tableRefs, currentTable, detailCtrl }: Props) {
  const auth = useAuth()
  const sessionId = useRef(`sess_${Date.now()}`)
  const [messages, setMessages] = useState<ChatMsg[]>([])
  const [inputText, setInputText] = useState('')
  const [sending, setSending] = useState(false)
  const scrollRef = useRef<HTMLDivElement>(null)

  function scrollBottom() {
    if (scrollRef.current) scrollRef.current.scrollTop = scrollRef.current.scrollHeight
  }

  async function sendMessage() {
    const text = inputText.trim()
    if (!text || sending) return
    setSending(true)
    try {
      const result = await sdbQuery(
        `INSERT INTO agent_message { user_input: $input, status: 'pending', session_id: $sid, created_by: $uid }`,
        { input: text, sid: sessionId.current, uid: auth.user?.id ?? '' },
        auth.token
      )
      setMessages(prev => [...prev, {
        id: result?.[0]?.id ?? '', role: 'user', text, status: 'pending',
        actions: [], timestamp: new Date().toISOString(),
      }])
      setInputText('')
      setTimeout(scrollBottom, 100)
    } catch (err: any) {
      console.error('[Chat] send failed:', err.message)
    } finally {
      setSending(false)
    }
  }

  function handleKeydown(e: React.KeyboardEvent) {
    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); sendMessage() }
  }

  const handleAgentResponse = useCallback((row: AgentMessage) => {
    setMessages(prev => [...prev, {
      id: row.id + '_agent', role: 'agent',
      text: row.response ?? '',
      status: (row.status as 'done' | 'error'),
      actions: row.actions || [],
      timestamp: row.created_at || '',
    }])
    dispatchActions(row.actions || [], {
      router: null as any,
      tableRefs: tableRefs.current,
      detailRef: detailCtrl,
    })
    setTimeout(scrollBottom, 100)
  }, [tableRefs, detailCtrl])

  useEffect(() => {
    if (!auth.token) return
    const unsub = subscribeAgentMessages(sessionId.current, (rows) => {
      for (const row of rows) handleAgentResponse(row)
    }, auth.token)
    return unsub
  }, [auth.token, handleAgentResponse])

  const noMessages = messages.length === 0

  return (
    <div style={{
      width: 380, minWidth: 380,
      borderLeft: '1px solid #e8e8e8',
      background: '#fff',
      display: 'flex', flexDirection: 'column',
      overflow: 'hidden',
    }}>
      {/* Header */}
      <div style={{
        padding: '12px 16px', fontWeight: 600, fontSize: 14,
        borderBottom: '1px solid #e8e8e8', flexShrink: 0,
        background: '#fafafa',
      }}>
        💬 对话
      </div>

      {/* Messages */}
      <div ref={scrollRef} style={{ flex: 1, overflowY: 'auto', padding: '12px 16px' }}>
        {noMessages && (
          <div style={{ textAlign: 'center', padding: '40px 0', color: '#bbb', fontSize: 13 }}>
            <div style={{ fontSize: 32, marginBottom: 8 }}>💬</div>
            <div>输入指令开始对话</div>
            <div style={{ fontSize: 12, marginTop: 4 }}>试试：「看库存」「新建客户张三」</div>
          </div>
        )}

        {messages.map(msg => (
          <div key={msg.id} style={{ marginBottom: 14 }}>
            <div style={{ display: 'flex', justifyContent: msg.role === 'user' ? 'flex-end' : 'flex-start' }}>
              <div style={{
                maxWidth: '90%', padding: '8px 14px', borderRadius: 12,
                background: msg.role === 'user' ? '#e8f0fe' : '#f1f3f4',
                fontSize: 13, lineHeight: 1.6, whiteSpace: 'pre-wrap', wordBreak: 'break-word',
              }}>
                {msg.status === 'pending' && <div style={{ color: '#999', fontSize: 11, marginBottom: 4 }}>⏳ 思考中...</div>}
                {msg.status === 'error' && <div style={{ color: '#d93025', fontSize: 11, marginBottom: 4 }}>⚠ 出错</div>}
                {msg.text}
                {msg.actions?.length > 0 && (
                  <div style={{ marginTop: 6, display: 'flex', gap: 4, flexWrap: 'wrap' }}>
                    {msg.actions.map((a, i) => (
                      <span key={i} style={{
                        padding: '2px 6px', background: '#e6f4ff', borderRadius: 4,
                        fontSize: 11, color: '#1677ff',
                      }}>{a.type}</span>
                    ))}
                  </div>
                )}
              </div>
            </div>
            <div style={{
              fontSize: 10, color: '#aaa', marginTop: 2,
              textAlign: msg.role === 'user' ? 'right' : 'left',
            }}>
              {msg.role === 'user' ? '我' : 'Agent'} {new Date(msg.timestamp).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })}
            </div>
          </div>
        ))}
      </div>

      {/* Input */}
      <div style={{
        borderTop: '1px solid #e0e0e0', padding: '10px 16px',
        background: '#fff', display: 'flex', gap: 8, alignItems: 'flex-end',
        flexShrink: 0,
      }}>
        <textarea
          value={inputText}
          onChange={e => setInputText(e.target.value)}
          onKeyDown={handleKeydown}
          placeholder="输入指令..."
          disabled={sending}
          rows={1}
          style={{
            flex: 1, padding: '8px 12px', border: '1px solid #d9d9d9',
            borderRadius: 18, fontSize: 13, resize: 'none',
            fontFamily: 'inherit', outline: 'none',
          }}
          onInput={e => {
            const el = e.currentTarget
            el.style.height = 'auto'
            el.style.height = Math.min(el.scrollHeight, 100) + 'px'
          }}
        />
        <button
          onClick={sendMessage}
          disabled={sending || !inputText.trim()}
          style={{
            padding: '8px 18px', background: sending ? '#91caff' : '#1677ff',
            color: '#fff', border: 'none', borderRadius: 18, fontSize: 13,
            cursor: sending ? 'not-allowed' : 'pointer', fontWeight: 500,
            whiteSpace: 'nowrap',
          }}
        >
          {sending ? '...' : '发送'}
        </button>
      </div>
    </div>
  )
}

// admin/src/controls/ChatPanel.vue
<script setup lang="ts">
/**
 * ChatPanel — 底部常驻对话面板
 *
 * 唯一的数据写入入口。用户输入自然语言 → INSERT agent_message → Agent 处理 → 结果回显。
 * 收到的 AgentResponse.actions 通过 emit 交给父组件（App.vue）的 ActionDispatcher 执行。
 */

import { ref, nextTick, watch, onMounted, onUnmounted } from 'vue'
import { NInput, NButton, NSpace, NTag, NSpin, useMessage } from 'naive-ui'
import { useSdbQuery } from '@/composables/useSdbQuery'
import { useAuthStore } from '@/stores/auth'
import { subscribeAgentMessages } from '@/agent/live-query'
import { tenantConfig } from '@/lib/tenant-config'
import type { AgentResponse } from '@/agent/types'

const { query } = useSdbQuery()
const auth = useAuthStore()
const message = useMessage()

const inputText = ref('')
const sending = ref(false)
const messages = ref<ChatMessage[]>([])

interface ChatMessage {
  id: string
  role: 'user' | 'agent'
  text: string
  status: 'pending' | 'done' | 'error'
  actions: any[]
  timestamp: string
}

const sessionId = ref(`sess_${Date.now()}`)
let unsubscribe: (() => void) | null = null

// ── 发消息 ──

async function sendMessage() {
  const text = inputText.value.trim()
  if (!text || sending.value) return

  sending.value = true
  try {
    const result = await query(
      `INSERT INTO agent_message {
        user_input: $input,
        status: 'pending',
        session_id: $sid,
        created_by: $uid
      }`,
      {
        input: text,
        sid: sessionId.value,
        uid: auth.user?.id ?? '',
      }
    )

    const newMsg = result?.[0]
    messages.value.push({
      id: newMsg?.id ?? '',
      role: 'user',
      text,
      status: 'pending',
      actions: [],
      timestamp: new Date().toISOString(),
    })

    inputText.value = ''
  } catch (err: any) {
    message.error('发送失败: ' + (err.message || ''))
  } finally {
    sending.value = false
  }
}

// ── 收 Agent 回复 ──

function handleAgentResponse(resp: AgentResponse) {
  // 更新或添加 agent 消息
  const existing = messages.value.find(m => m.id === resp.message_id)
  const agentMsg: ChatMessage = {
    id: resp.message_id + '_agent',
    role: 'agent',
    text: resp.reply,
    status: resp.status,
    actions: resp.actions || [],
    timestamp: new Date().toISOString(),
  }

  if (existing) {
    existing.status = resp.status
  }
  messages.value.push(agentMsg)

  // 将 actions 交给父组件分发
  emit('actions', resp.actions, resp)
}

const emit = defineEmits<{
  (e: 'actions', actions: any[], response: AgentResponse): void
}>()

// ── 订阅 LIVE QUERY ──
// 只在已登录时启动

onMounted(() => {
  if (!auth.token) return
  unsubscribe = subscribeAgentMessages(
    sessionId.value,
    (rows) => {
      for (const row of rows) {
        const resp: AgentResponse = {
          message_id: row.id,
          status: row.status as 'done' | 'error',
          reply: row.response ?? '',
          actions: row.actions || [],
        }
        handleAgentResponse(resp)
      }
    },
    auth.token ?? '',
  )
})

onUnmounted(() => {
  unsubscribe?.()
})

// ── 滚动到底部 ──

const chatContainer = ref<HTMLElement>()

watch(() => messages.value.length, async () => {
  await nextTick()
  if (chatContainer.value) {
    chatContainer.value.scrollTop = chatContainer.value.scrollHeight
  }
})

function handleKeydown(e: KeyboardEvent) {
  if (e.key === 'Enter' && !e.shiftKey) {
    e.preventDefault()
    sendMessage()
  }
}
</script>

<template>
  <div class="chat-panel">
    <!-- 消息列表 -->
    <div ref="chatContainer" class="chat-messages">
      <div v-if="messages.length === 0" class="chat-empty">
        <p>💬 对话即操作。</p>
        <p style="color: #999; font-size: 13px">
          试试：「看库存」「新建客户张三」「书院旗舰店库存低于5的商品」
        </p>
      </div>

      <div
        v-for="msg in messages"
        :key="msg.id"
        :class="['chat-bubble', msg.role]"
      >
        <div class="bubble-meta">
          <n-tag :type="msg.role === 'user' ? 'info' : 'success'" size="tiny">
            {{ msg.role === 'user' ? '我' : 'Agent' }}
          </n-tag>
          <n-tag v-if="msg.status === 'pending'" type="warning" size="tiny">
            <n-spin :size="12" />
          </n-tag>
          <n-tag v-if="msg.status === 'error'" type="error" size="tiny">失败</n-tag>
        </div>
        <div class="bubble-text">{{ msg.text }}</div>
        <!-- actions 预览 -->
        <div v-if="msg.actions && msg.actions.length > 0" class="bubble-actions">
          <n-tag
            v-for="(action, i) in msg.actions"
            :key="i"
            size="tiny"
            :bordered="false"
          >
            {{ action.type }}
          </n-tag>
        </div>
      </div>
    </div>

    <!-- 输入区 -->
    <div class="chat-input">
      <n-input
        v-model:value="inputText"
        type="textarea"
        placeholder="输入指令... (Enter 发送，Shift+Enter 换行)"
        :autosize="{ minRows: 1, maxRows: 4 }"
        :disabled="sending"
        @keydown="handleKeydown"
      />
      <n-button
        type="primary"
        :loading="sending"
        :disabled="!inputText.trim()"
        @click="sendMessage"
        style="margin-left: 8px"
      >
        发送
      </n-button>
    </div>
  </div>
</template>

<style scoped>
.chat-panel {
  display: flex;
  flex-direction: column;
  height: 100%;
  max-height: 40vh;
  border-top: 1px solid #e8e8e8;
  background: #fafafa;
}

.chat-messages {
  flex: 1;
  overflow-y: auto;
  padding: 12px 16px;
}

.chat-empty {
  text-align: center;
  padding: 24px;
  color: #666;
}

.chat-bubble {
  margin-bottom: 12px;
  padding: 8px 12px;
  border-radius: 8px;
  max-width: 80%;
}

.chat-bubble.user {
  background: #e6f7ff;
  margin-left: auto;
}

.chat-bubble.agent {
  background: #f6ffed;
  margin-right: auto;
}

.bubble-meta {
  display: flex;
  gap: 6px;
  margin-bottom: 4px;
}

.bubble-text {
  white-space: pre-wrap;
  line-height: 1.5;
}

.bubble-actions {
  margin-top: 6px;
  display: flex;
  gap: 4px;
  flex-wrap: wrap;
}

.chat-input {
  display: flex;
  align-items: flex-end;
  padding: 8px 16px;
  background: #fff;
  border-top: 1px solid #e8e8e8;
}

.chat-input :deep(.n-input) {
  flex: 1;
}
</style>
