// admin-react/src/components/SchemaTable.tsx
import { useState, useEffect, useCallback, forwardRef, useImperativeHandle } from 'react'
import { useAuth } from '@/stores/auth'
import { sdbQuery } from '@/lib/sdb'
import type { TableMeta, FieldMeta } from '@/lib/schema'
import { extractEnumValues } from '@/lib/schema'

interface Props {
  tableName: string
  meta: TableMeta | null
  onRowClick: (recordId: string) => void
}

export interface TableController {
  setFilter: (field: string, value: string) => void
  highlightRows: (rowIds: string[]) => void
  refresh: () => void
}

const LABEL_MAP: Record<string, string> = {
  'active': '激活', 'inactive': '禁用',
  '上架': '上架', '下架': '下架',
  'pending': '待处理', 'done': '已完成',
  '已发货': '已发货', '待付款': '待付款', '已完成': '已完成', '已取消': '已取消',
}

function renderCell(row: any, field: FieldMeta): string {
  const val = row[field.name]
  if (val === null || val === undefined) return '-'
  if (field.isRecord && typeof val === 'object' && val !== null) {
    return val.name || val.id || '-'
  }
  if (field.assert) {
    const enums = extractEnumValues(field.assert)
    if (enums.length > 0 && enums.length <= 8) {
      return LABEL_MAP[val] || String(val)
    }
  }
  if (typeof val === 'boolean') return val ? '是' : '否'
  return String(val)
}

const SchemaTable = forwardRef<TableController, Props>(({ tableName, meta, onRowClick }, ref) => {
  const { token } = useAuth()
  const [rows, setRows] = useState<any[]>([])
  const [loading, setLoading] = useState(false)
  const [searchText, setSearchText] = useState('')
  const [page, setPage] = useState(1)
  const [totalCount, setTotalCount] = useState(0)
  const [highlighted, setHighlighted] = useState<string[]>([])
  const PAGE_SIZE = 20

  const fetchData = useCallback(async () => {
    if (!tableName) return
    setLoading(true)
    try {
      const text = searchText.trim()
      let where = ''
      let vars: Record<string, unknown> | undefined
      if (text && meta) {
        const stringFields = meta.fields.filter(f => f.kind.includes('string') || f.kind.includes('text'))
        if (stringFields.length > 0) {
          where = `WHERE (${stringFields.map(f => `${f.name} CONTAINS $search`).join(' OR ')})`
          vars = { search: text }
        }
      }

      const countSql = where
        ? `SELECT count() FROM ${tableName} ${where} GROUP ALL`
        : `SELECT count() FROM ${tableName} GROUP ALL`
      const countResult = await sdbQuery(countSql, vars, token)
      setTotalCount(countResult?.[0]?.count ?? 0)

      const dataSql = `SELECT * FROM ${tableName} ${where} ORDER BY created_at DESC LIMIT ${PAGE_SIZE} START ${(page - 1) * PAGE_SIZE}`
      const data = await sdbQuery(dataSql, vars, token) || []
      setRows(data)
    } catch (err: any) {
      console.error(`[SchemaTable] ${tableName}:`, err.message)
      setRows([])
      setTotalCount(0)
    } finally {
      setLoading(false)
    }
  }, [tableName, searchText, page, token, meta])

  useEffect(() => { fetchData() }, [fetchData])

  // Debounce search
  useEffect(() => {
    const t = setTimeout(() => { setPage(1); fetchData() }, 300)
    return () => clearTimeout(t)
  }, [searchText])

  useImperativeHandle(ref, () => ({
    setFilter(_field: string, value: string) { setSearchText(value) },
    highlightRows(ids: string[]) { setHighlighted(ids) },
    refresh() { fetchData() },
  }), [fetchData])

  const totalPages = Math.ceil(totalCount / PAGE_SIZE)

  if (!meta) return <div style={{ padding: 40, textAlign: 'center', color: '#999' }}>加载中...</div>

  return (
    <div>
      {/* Toolbar */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }}>
        <div style={{ display: 'flex', gap: 8 }}>
          <input
            type="text"
            value={searchText}
            onChange={e => setSearchText(e.target.value)}
            placeholder="搜索..."
            style={{ width: 240, padding: '8px 12px', border: '1px solid #d9d9d9', borderRadius: 6, fontSize: 14 }}
          />
        </div>
        <div style={{ display: 'flex', gap: 8, alignItems: 'center', fontSize: 14, color: '#666' }}>
          <button disabled={page <= 1} onClick={() => setPage(p => p - 1)}
            style={{ width: 36, height: 36, border: '1px solid #d9d9d9', background: '#fff', borderRadius: 6, fontSize: 18, cursor: page <= 1 ? 'default' : 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' }}
          >‹</button>
          <span style={{ minWidth: 60, textAlign: 'center' }}>{page} / {totalPages || 1}</span>
          <button disabled={page >= totalPages} onClick={() => setPage(p => p + 1)}
            style={{ width: 36, height: 36, border: '1px solid #d9d9d9', background: '#fff', borderRadius: 6, fontSize: 18, cursor: page >= totalPages ? 'default' : 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' }}
          >›</button>
          <span style={{ marginLeft: 8 }}>共 {totalCount} 条</span>
        </div>
      </div>

      {/* Table */}
      <div style={{ overflowX: 'auto' }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
          <thead>
            <tr style={{ background: '#fafafa', borderBottom: '2px solid #e8e8e8' }}>
              {meta.fields.map(f => (
                <th key={f.name} style={{
                  padding: '8px 12px', textAlign: 'left', fontWeight: 600,
                  color: '#555', whiteSpace: 'nowrap', minWidth: f.name === 'id' ? 180 : 100
                }}>
                  {f.comment || f.name}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr><td colSpan={meta.fields.length} style={{ padding: 40, textAlign: 'center', color: '#999' }}>加载中...</td></tr>
            ) : rows.length === 0 ? (
              <tr><td colSpan={meta.fields.length} style={{ padding: 40, textAlign: 'center', color: '#bbb' }}>暂无数据</td></tr>
            ) : rows.map(row => (
              <tr
                key={row.id}
                onClick={() => onRowClick(row.id)}
                style={{
                  cursor: 'pointer',
                  background: highlighted.includes(row.id) ? '#fff3cd' : undefined,
                  borderBottom: '1px solid #f0f0f0',
                }}
                onMouseEnter={e => { if (!highlighted.includes(row.id)) (e.currentTarget as HTMLElement).style.background = '#f5f5f5' }}
                onMouseLeave={e => { if (!highlighted.includes(row.id)) (e.currentTarget as HTMLElement).style.background = '' }}
              >
                {meta.fields.map(f => (
                  <td key={f.name} style={{ padding: '6px 12px', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', maxWidth: 200 }}>
                    {renderCell(row, f)}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
})

export default SchemaTable

// admin/src/controls/SchemaTable.vue
<script setup lang="ts">
/**
 * SchemaTable — 零配置表格
 *
 * 从 table meta 自动生成列定义、搜索、排序、分页。
 * 接受 Agent 发来的 filter / highlight action。
 */
import { ref, computed, watch, h } from 'vue'
import { NDataTable, NInput, NButton, NSpace, NPagination } from 'naive-ui'
import type { DataTableColumn } from 'naive-ui'
import { useSdbQuery } from '@/composables/useSdbQuery'
import type { TableMeta, FieldMeta } from '@/lib/schema'
import { extractEnumValues } from '@/lib/schema'

const props = defineProps<{
  tableName: string
  meta: TableMeta | null
}>()

const emit = defineEmits<{
  (e: 'rowClick', recordId: string): void
  (e: 'create'): void
}>()

const { query } = useSdbQuery()

const rows = ref<any[]>([])
const totalCount = ref(0)
const loading = ref(false)
const searchText = ref('')
const page = ref(1)
const pageSize = ref(20)
const highlightedRowIds = ref<string[]>([])

// ── 动态生成列定义 ──

const columns = computed<DataTableColumn<any>[]>(() => {
  if (!props.meta) return []

  return props.meta.fields.map((field) => {
    const col: DataTableColumn<any> = {
      title: field.comment || field.name,
      key: field.name,
      width: columnWidth(field),
      resizable: true,
      sorter: isSortable(field),
      ellipsis: { tooltip: true },
    }

    // 枚举列 → 中文显示
    if (field.assert) {
      const enumValues = extractEnumValues(field.assert)
      if (enumValues.length > 0 && enumValues.length <= 8) {
        col.render = (row: any) => {
          const val = row[field.name]
          const labelMap: Record<string, string> = {
            'active': '激活', 'inactive': '禁用',
            '上架': '上架', '下架': '下架',
            'pending': '待处理', 'done': '已完成',
            '已发货': '已发货', '待付款': '待付款', '已完成': '已完成', '已取消': '已取消',
          }
          return h('span', null, labelMap[val] || val || '-')
        }
      }
    }

    // record 类型 → 显示关联名称
    if (field.isRecord && field.recordTarget) {
      col.render = (row: any) => {
        const nested = row[field.name]
        if (typeof nested === 'object' && nested !== null) {
          return h('span', null, nested.name || nested.id || '-')
        }
        return h('span', null, nested || '-')
      }
    }

    return col
  })
})

function columnWidth(field: FieldMeta): number {
  if (['int', 'float', 'decimal', 'bool'].includes(field.kind)) return 100
  if (field.kind === 'datetime') return 160
  if (field.isRecord) return 160
  if (field.name === 'id') return 200
  if (['name', 'title'].includes(field.name)) return 200
  return 150
}

function isSortable(field: FieldMeta): boolean {
  return ['string', 'int', 'float', 'decimal', 'datetime'].some(t => field.kind.includes(t))
}

// ── 构建搜索 SQL ──

function buildWhereClause(): string {
  const text = searchText.value.trim()
  if (!text || !props.meta) return ''

  const clauses: string[] = []
  for (const field of props.meta.fields) {
    if (['string', 'text'].some(t => field.kind.includes(t))) {
      clauses.push(`${field.name} CONTAINS $search`)
    }
  }
  return clauses.length > 0 ? `WHERE (${clauses.join(' OR ')})` : ''
}

// ── 数据加载 ──

let fetchTimer: ReturnType<typeof setTimeout> | null = null

async function fetchData() {
  if (!props.tableName) return
  loading.value = true
  try {
    const where = buildWhereClause()
    const esc = (s: string) => s.replace(/'/g, "\\'").replace(/"/g, '\\"')

    // 查总数
    const countSql = where
      ? `SELECT count() FROM ${props.tableName} ${where}`
      : `SELECT count() FROM ${props.tableName}`
    const countResult = await query(countSql, where ? { search: esc(searchText.value.trim()) } : undefined)
    totalCount.value = countResult?.[0]?.count ?? 0

    // 查数据
    const dataSql = `SELECT * FROM ${props.tableName} ${where} ORDER BY created_at DESC LIMIT ${pageSize.value} START ${(page.value - 1) * pageSize.value}`
    const rows = await query(dataSql, where ? { search: esc(searchText.value.trim()) } : undefined) || []
    rows.value = rows
  } catch (err: any) {
    console.error(`[SchemaTable] load ${props.tableName} failed:`, err.message)
    rows.value = []
    totalCount.value = 0
  } finally {
    loading.value = false
  }
}

// Debounce search
watch(searchText, () => {
  page.value = 1
  if (fetchTimer) clearTimeout(fetchTimer)
  fetchTimer = setTimeout(fetchData, 300)
})

watch(() => props.tableName, () => {
  searchText.value = ''
  page.value = 1
  highlightedRowIds.value = []
  fetchData()
}, { immediate: true })

watch(page, fetchData)

// ── 行点击 → 打开详情 ──

function handleRowClick(row: any) {
  emit('rowClick', row.id)
}

// ── 行样式（高亮） ──

const rowProps = (row: any) => {
  const isHighlighted = highlightedRowIds.value.includes(row.id)
  return {
    style: isHighlighted ? 'background: #fff3cd; cursor: pointer' : 'cursor: pointer',
    onClick: () => handleRowClick(row),
  }
}

// ── 对外暴露的 TableController 接口 ──

defineExpose({
  setFilter(field: string, value: string) {
    // Agent 的 filter action → 设置搜索文本
    searchText.value = value
  },
  highlightRows(rowIds: string[]) {
    highlightedRowIds.value = rowIds
  },
  refresh() {
    fetchData()
  },
  downloadCSV(_sql: string, _filename?: string) {
    // TODO: 实现 CSV 导出
  },
  openCreate() {
    emit('create')
  },
})
</script>

<template>
  <div class="schema-table">
    <n-space style="margin-bottom: 12px" align="center" justify="space-between">
      <n-space align="center">
        <n-input
          v-model:value="searchText"
          placeholder="搜索..."
          clearable
          style="width: 240px"
        />
        <n-button type="primary" size="small" @click="emit('create')">
          + 新建
        </n-button>
      </n-space>
      <n-pagination
        v-model:page="page"
        :page-size="pageSize"
        :item-count="totalCount"
        size="small"
      />
    </n-space>

    <n-data-table
      :columns="columns"
      :data="rows"
      :loading="loading"
      :row-key="(row: any) => row.id"
      :row-props="rowProps"
      :single-line="false"
      size="small"
    />
  </div>
</template>

<style scoped>
.schema-table {
  height: 100%;
  display: flex;
  flex-direction: column;
}
</style>
